-- MySQL Script generated by MySQL Workbench
-- Mon Dec  6 19:28:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema publicarte_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema publicarte_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `publicarte_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `publicarte_db` ;

-- -----------------------------------------------------
-- Table `publicarte_db`.`brands`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `publicarte_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `publicarte_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `avatar` VARCHAR(255) NOT NULL,
  `rolesId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `rolesId` (`rolesId` ASC) VISIBLE,
  CONSTRAINT `users_ibfk_1`
    FOREIGN KEY (`rolesId`)
    REFERENCES `publicarte_db`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `publicarte_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `publicarte_db`.`producers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`producers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usersId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usersId` (`usersId` ASC) VISIBLE,
  CONSTRAINT `producers_ibfk_1`
    FOREIGN KEY (`usersId`)
    REFERENCES `publicarte_db`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `publicarte_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  `categoriesId` INT NOT NULL,
  `producersId` INT NOT NULL,
  `brandsId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoriesId` (`categoriesId` ASC) VISIBLE,
  INDEX `producersId` (`producersId` ASC) VISIBLE,
  INDEX `brandsId` (`brandsId` ASC) VISIBLE,
  CONSTRAINT `products_ibfk_1`
    FOREIGN KEY (`categoriesId`)
    REFERENCES `publicarte_db`.`categories` (`id`),
  CONSTRAINT `products_ibfk_2`
    FOREIGN KEY (`producersId`)
    REFERENCES `publicarte_db`.`producers` (`id`),
  CONSTRAINT `products_ibfk_3`
    FOREIGN KEY (`brandsId`)
    REFERENCES `publicarte_db`.`brands` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `publicarte_db`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `total_price` INT NOT NULL,
  `usersId` INT NOT NULL,
  `productsId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usersId` (`usersId` ASC) VISIBLE,
  INDEX `productsId` (`productsId` ASC) VISIBLE,
  CONSTRAINT `carts_ibfk_1`
    FOREIGN KEY (`usersId`)
    REFERENCES `publicarte_db`.`users` (`id`),
  CONSTRAINT `carts_ibfk_2`
    FOREIGN KEY (`productsId`)
    REFERENCES `publicarte_db`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `publicarte_db`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file` VARCHAR(255) NOT NULL,
  `productsId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `productsId` (`productsId` ASC) VISIBLE,
  CONSTRAINT `images_ibfk_1`
    FOREIGN KEY (`productsId`)
    REFERENCES `publicarte_db`.`products` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `publicarte_db`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usersId` INT NOT NULL,
  `cartsId` INT NOT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usersId` (`usersId` ASC) VISIBLE,
  INDEX `cartsId` (`cartsId` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`usersId`)
    REFERENCES `publicarte_db`.`users` (`id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`cartsId`)
    REFERENCES `publicarte_db`.`carts` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `publicarte_db`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `publicarte_db`.`sequelizemeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

