-- MySQL Script generated by MySQL Workbench
-- Thu Nov 11 23:25:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema publicarte
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `publicarte` ;

-- -----------------------------------------------------
-- Schema publicarte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `publicarte` DEFAULT CHARACTER SET utf8 ;
USE `publicarte` ;

-- -----------------------------------------------------
-- Table `publicarte`.`brands`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicarte`.`brands` ;

CREATE TABLE IF NOT EXISTS `publicarte`.`brands` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `publicarte`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicarte`.`roles` ;

CREATE TABLE IF NOT EXISTS `publicarte`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `publicarte`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicarte`.`users` ;

CREATE TABLE IF NOT EXISTS `publicarte`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `avatar` VARCHAR(100) NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_type_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `FK_id_role`
    FOREIGN KEY (`id_role`)
    REFERENCES `publicarte`.`roles` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `publicarte`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicarte`.`categories` ;

CREATE TABLE IF NOT EXISTS `publicarte`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `publicarte`.`producers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicarte`.`producers` ;

CREATE TABLE IF NOT EXISTS `publicarte`.`producers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_user_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `FK_id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `publicarte`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `publicarte`.`products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicarte`.`products` ;

CREATE TABLE IF NOT EXISTS `publicarte`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NOT NULL,
  `price` INT NOT NULL,
  `id_category` INT NOT NULL,
  `id_producer` INT NOT NULL,
  `id_brand` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_products_categories_idx` (`id_category` ASC) VISIBLE,
  INDEX `FK_id_productor_idx` (`id_producer` ASC) VISIBLE,
  INDEX `FK_id_brand_idx` (`id_brand` ASC) VISIBLE,
  CONSTRAINT `FK_id_brand`
    FOREIGN KEY (`id_brand`)
    REFERENCES `publicarte`.`brands` (`id`),
  CONSTRAINT `FK_id_category`
    FOREIGN KEY (`id_category`)
    REFERENCES `publicarte`.`categories` (`id`),
  CONSTRAINT `FK_id_producer`
    FOREIGN KEY (`id_producer`)
    REFERENCES `publicarte`.`producers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `publicarte`.`carts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicarte`.`carts` ;

CREATE TABLE IF NOT EXISTS `publicarte`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `amount` INT NOT NULL,
  `total_price` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_first_name_idx` (`id_user` ASC) VISIBLE,
  INDEX `FK_id_product_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `FK_id_first_name`
    FOREIGN KEY (`id_user`)
    REFERENCES `publicarte`.`users` (`id`),
  CONSTRAINT `FK_id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `publicarte`.`products` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `publicarte`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicarte`.`orders` ;

CREATE TABLE IF NOT EXISTS `publicarte`.`orders` (
  `id` INT NOT NULL,
  `id_user` INT NOT NULL,
  `id_cart` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_user_idx` (`id_user` ASC) VISIBLE,
  INDEX `FK_cart_idx` (`id_cart` ASC) VISIBLE,
  CONSTRAINT `FK_cart`
    FOREIGN KEY (`id_cart`)
    REFERENCES `publicarte`.`carts` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `FK_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `publicarte`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `publicarte`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `publicarte`.`images` ;

CREATE TABLE IF NOT EXISTS `publicarte`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `archivo` VARCHAR(100) NOT NULL,
  `id_product` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_id_image_idx` (`id_product` ASC) VISIBLE,
  CONSTRAINT `FK_id_image`
    FOREIGN KEY (`id_product`)
    REFERENCES `publicarte`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;